# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  nodeVersion: "16"
  cmakeVersion: "3.22.x"
  flutterVersion: "3.3.10"

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.nodeVersion }}
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: ${{ env.cmakeVersion }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutterVersion }}
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - name: Npm install
        run: npm install
      - name: Build Cli Vendor Appc
        run: sh build_macos.sh
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./platforms/cli-macos/package.json
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.nodeVersion }}
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: ${{ env.cmakeVersion }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutterVersion }}
      - name: Install gtk
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter doctor -v
      - name: Npm install
        run: npm install
      - name: Build Cli Vendor App
        run: bash build_linux.sh
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./platforms/cli-linux/package.json
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.nodeVersion }}
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: ${{ env.cmakeVersion }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutterVersion }}
      - run: flutter config --enable-windows-desktop
      - run: flutter doctor -v
      - name: Npm install
        run: npm install
      - name: Build Cli Vendor Appc
        run: powershell build_windows.ps1
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./platforms/cli-windows/package.json
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}